name: Pages

on:
  pull_request:
  push:
  schedule:
    - cron:  '30 18 * * *'

jobs:
  test:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Build Packages
        run: |
          python -m pip install -r requirements.txt
          mkdir -p build
          python build.py
          python build.py GMK 30

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            cname: isbk.gadgetoid.com
